import 'package:get/get_navigation/src/root/internacionalization.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en': {
      'identifyMedication': 'Identify Your Medication Instantly',
      'scanDescription':
          'Scan any pill bottle or package with AI and get accurate details, dosage, and safety information right on your device.',
      'signIn': 'Sign In',
      'email': 'Email',
      'password': 'Password',
      'rememberMe': 'Remember me',
      'forgotPassword': 'Forgot password?',
      'login': 'Login',
      'dontHaveAccount': 'Dont have any account?',
      'signUp': 'Sign Up',
      'forgotPasswordTitle':
          'Provide the email linked to your account. Well send a password reset link to your inbox.',
      'verifyCode': 'Verify code',
      'checkYourEmail': 'Check your email',
      'resetLinkSent':
          'We sent a reset link to mytrek@gmail.com. Enter the 5 digit code that is mentioned in the email.',
      'havenotReceivedEmail': 'Haven t got the email yet?',
      'resendCode': 'Resend code',
      'setNewPassword': 'Set new password',
      'newPasswordHint': 'Please enter a new password and re-enter to confirm.',
      'newPassword': 'New Password',
      'confirmPassword': 'Confirm Password',
      'continue': 'Continue',
      'congratulations': 'Congratulations!',
      'passwordChanged': 'Password Changed',
      'signUpForm': 'Sign up',
      'name': 'Name',
      'confirmPasswordHint': 'Confirm Password',
      'signUpButton': 'Sign up',
      'hello': 'Hello',
      'healthWealth': 'Your health is your greatest wealth',
      'scanMedication': 'Scan Medication',
      'scan': 'Scan',
      'viewDetails': 'View details',
      'dosage': 'Dosage',
      'genericName': 'Generic Name',
      'manufacturer': 'Manufacturer',
      'drugClass': 'Drug Class',
      'uses': 'Uses',
      'dosageInfo': 'Dosage Information',
      'howToTake': 'How to Take',
      'sideEffects': 'Side Effects',
      'warnings': 'Warnings',
      'storageInstructions': 'Storage Instructions',
      'interactions': 'Interactions',
      'save': 'Save',
      'home': 'Home',
      'medications': 'Medications',
      'settings': 'Settings',
      'checkInfo': 'Check info',
      'editProfile': 'Edit Profile',
      'languageSelection': 'Language Selection',
      'aboutUs': 'About Us',
      'contactUs': 'Contact Us',
      'notification': 'Notification',
      'logout': 'Logout',
      'changePhoto': 'Change photo',
      'fullName': 'Full name',
      'saveChanges': 'Save changes',
      'searchLanguage': 'Search language',
      'english': 'English',
      'spanish': 'Spanish',
      'french': 'French',
      'german': 'German',
      'chinese': 'Chinese',
      'creole': 'Creole',
      'russian': 'Russian',
      'portuguese': 'Portuguese',
    },
    'es': {
      'identifyMedication': 'Identifique su medicación instantáneamente',
      'scanDescription':
          'Escanee cualquier frasco de pastillas o paquete con IA y obtenga detalles precisos, dosificación e información de seguridad en su dispositivo.',
      'signIn': 'Iniciar sesión',
      'email': 'Correo electrónico',
      'password': 'Contraseña',
      'rememberMe': 'Recuérdame',
      'forgotPassword': '¿Olvidaste tu contraseña?',
      'login': 'Iniciar sesión',
      'dontHaveAccount': '¿No tienes una cuenta?',
      'signUp': 'Registrarse',
      'forgotPasswordTitle':
          'Proporcione el correo electrónico vinculado a su cuenta. Le enviaremos un enlace de restablecimiento de contraseña a su bandeja de entrada.',
      'verifyCode': 'Verificar código',
      'checkYourEmail': 'Revisa tu correo electrónico',
      'resetLinkSent':
          'Enviamos un enlace de restablecimiento a mytrek@gmail.com. Ingresa el código de 5 dígitos mencionado en el correo electrónico.',
      'havenotReceivedEmail': '¿No has recibido el correo?',
      'resendCode': 'Reenviar código',
      'setNewPassword': 'Establecer nueva contraseña',
      'newPasswordHint':
          'Por favor ingresa una nueva contraseña y vuélvela a ingresar para confirmarla.',
      'newPassword': 'Nueva contraseña',
      'confirmPassword': 'Confirmar contraseña',
      'continue': 'Continuar',
      'congratulations': '¡Felicidades!',
      'passwordChanged': 'Contraseña cambiada',
      'signUpForm': 'Formulario de registro',
      'name': 'Nombre',
      'confirmPasswordHint': 'Confirmar contraseña',
      'signUpButton': 'Registrarse',
      'hello': 'Hola',
      'healthWealth': 'Tu salud es tu mayor riqueza',
      'scanMedication': 'Escanear medicación',
      'scan': 'Escanear',
      'viewDetails': 'Ver detalles',
      'dosage': 'Dosificación',
      'genericName': 'Nombre genérico',
      'manufacturer': 'Fabricante',
      'drugClass': 'Clase de medicamento',
      'uses': 'Usos',
      'dosageInfo': 'Información sobre la dosificación',
      'howToTake': 'Cómo tomar',
      'sideEffects': 'Efectos secundarios',
      'warnings': 'Advertencias',
      'storageInstructions': 'Instrucciones de almacenamiento',
      'interactions': 'Interacciones',
      'save': 'Guardar',
      'home': 'Inicio',
      'medications': 'Medicamentos',
      'settings': 'Configuraciones',
      'checkInfo': 'Comprobar información',
      'editProfile': 'Editar perfil',
      'languageSelection': 'Selección de idioma',
      'aboutUs': 'Acerca de nosotros',
      'contactUs': 'Contáctenos',
      'notification': 'Notificación',
      'logout': 'Cerrar sesión',
      'changePhoto': 'Cambiar foto',
      'fullName': 'Nombre completo',
      'saveChanges': 'Guardar cambios',
      'searchLanguage': 'Buscar idioma',
      'english': 'Inglés',
      'spanish': 'Español',
      'french': 'Francés',
      'german': 'Alemán',
      'chinese': 'Chino',
      'creole': 'Criollo',
      'russian': 'Ruso',
      'portuguese': 'Portugués',
    },
    'fr': {
      'identifyMedication': 'Identifiez instantanément votre médicament',
      'scanDescription':
          'Scannez n\'importe quel flacon de pilules ou paquet avec l\'IA et obtenez des détails précis, des doses et des informations sur la sécurité directement sur votre appareil.',
      'signIn': 'Se connecter',
      'email': 'E-mail',
      'password': 'Mot de passe',
      'rememberMe': 'Souviens-toi de moi',
      'forgotPassword': 'Mot de passe oublié ?',
      'login': 'Se connecter',
      'dontHaveAccount': 'Vous n\'avez pas de compte ?',
      'signUp': 'S\'inscrire',
      'forgotPasswordTitle':
          'Fournissez l\'email lié à votre compte. Nous vous enverrons un lien de réinitialisation de mot de passe dans votre boîte de réception.',
      'verifyCode': 'Vérifier le code',
      'checkYourEmail': 'Vérifiez votre e-mail',
      'resetLinkSent':
          'Nous avons envoyé un lien de réinitialisation à mytrek@gmail.com. Entrez le code à 5 chiffres mentionné dans l\'email.',
      'havenotReceivedEmail': 'Vous n\'avez pas reçu l\'e-mail ?',
      'resendCode': 'Renvoyer le code',
      'setNewPassword': 'Définir un nouveau mot de passe',
      'newPasswordHint':
          'Veuillez entrer un nouveau mot de passe et le saisir à nouveau pour le confirmer.',
      'newPassword': 'Nouveau mot de passe',
      'confirmPassword': 'Confirmer le mot de passe',
      'continue': 'Continuer',
      'congratulations': 'Félicitations !',
      'passwordChanged': 'Mot de passe changé',
      'signUpForm': 'Formulaire d\'inscription',
      'name': 'Nom',
      'confirmPasswordHint': 'Confirmer le mot de passe',
      'signUpButton': 'S\'inscrire',
      'hello': 'Bonjour',
      'healthWealth': 'Votre santé est votre plus grande richesse',
      'scanMedication': 'Scanner un médicament',
      'scan': 'Scanner',
      'viewDetails': 'Voir les détails',
      'dosage': 'Dosage',
      'genericName': 'Nom générique',
      'manufacturer': 'Fabricant',
      'drugClass': 'Classe de médicament',
      'uses': 'Utilisations',
      'dosageInfo': 'Informations sur la posologie',
      'howToTake': 'Comment prendre',
      'sideEffects': 'Effets secondaires',
      'warnings': 'Avertissements',
      'storageInstructions': 'Instructions de stockage',
      'interactions': 'Interactions',
      'save': 'Enregistrer',
      'home': 'Accueil',
      'medications': 'Médicaments',
      'settings': 'Paramètres',
      'checkInfo': 'Vérifier les informations',
      'editProfile': 'Modifier le profil',
      'languageSelection': 'Sélection de la langue',
      'aboutUs': 'À propos de nous',
      'contactUs': 'Nous contacter',
      'notification': 'Notification',
      'logout': 'Se déconnecter',
      'changePhoto': 'Changer la photo',
      'fullName': 'Nom complet',
      'saveChanges': 'Sauvegarder les modifications',
      'searchLanguage': 'Rechercher une langue',
      'english': 'Anglais',
      'spanish': 'Espagnol',
      'french': 'Français',
      'german': 'Allemand',
      'chinese': 'Chinois',
      'creole': 'Créole',
      'russian': 'Russe',
      'portuguese': 'Portugais',
    },
    'pt': {
      'identifyMedication': 'Identifique seu medicamento instantaneamente',
      'scanDescription':
          'Escaneie qualquer frasco de pílulas ou embalagem com IA e obtenha detalhes precisos, dosagem e informações de segurança diretamente no seu dispositivo.',
      'signIn': 'Entrar',
      'email': 'E-mail',
      'password': 'Senha',
      'rememberMe': 'Lembre de mim',
      'forgotPassword': 'Esqueceu sua senha?',
      'login': 'Entrar',
      'dontHaveAccount': 'Não tem uma conta?',
      'signUp': 'Cadastre-se',
      'forgotPasswordTitle':
          'Forneça o e-mail vinculado à sua conta. Enviaremos um link de redefinição de senha para sua caixa de entrada.',
      'verifyCode': 'Verificar código',
      'checkYourEmail': 'Verifique seu e-mail',
      'resetLinkSent':
          'Enviamos um link de redefinição para mytrek@gmail.com. Digite o código de 5 dígitos mencionado no e-mail.',
      'havenotReceivedEmail': 'Não recebeu o e-mail?',
      'resendCode': 'Reenviar código',
      'setNewPassword': 'Defina uma nova senha',
      'newPasswordHint':
          'Por favor, insira uma nova senha e insira novamente para confirmar.',
      'newPassword': 'Nova Senha',
      'confirmPassword': 'Confirmar Senha',
      'continue': 'Continuar',
      'congratulations': 'Parabéns!',
      'passwordChanged': 'Senha alterada',
      'signUpForm': 'Formulário de cadastro',
      'name': 'Nome',
      'confirmPasswordHint': 'Confirmar Senha',
      'signUpButton': 'Cadastrar',
      'hello': 'Olá',
      'healthWealth': 'Sua saúde é sua maior riqueza',
      'scanMedication': 'Escanear Medicamento',
      'scan': 'Escanear',
      'viewDetails': 'Ver detalhes',
      'dosage': 'Dosagem',
      'genericName': 'Nome Genérico',
      'manufacturer': 'Fabricante',
      'drugClass': 'Classe de Medicamento',
      'uses': 'Usos',
      'dosageInfo': 'Informações sobre dosagem',
      'howToTake': 'Como tomar',
      'sideEffects': 'Efeitos colaterais',
      'warnings': 'Avisos',
      'storageInstructions': 'Instruções de armazenamento',
      'interactions': 'Interações',
      'save': 'Salvar',
      'home': 'Início',
      'medications': 'Medicamentos',
      'settings': 'Configurações',
      'checkInfo': 'Verificar informações',
      'editProfile': 'Editar perfil',
      'languageSelection': 'Seleção de idioma',
      'aboutUs': 'Sobre nós',
      'contactUs': 'Contate-nos',
      'notification': 'Notificação',
      'logout': 'Sair',
      'changePhoto': 'Alterar foto',
      'fullName': 'Nome completo',
      'saveChanges': 'Salvar alterações',
      'searchLanguage': 'Pesquisar idioma',
      'english': 'Inglês',
      'spanish': 'Espanhol',
      'french': 'Francês',
      'german': 'Alemão',
      'chinese': 'Chinês',
      'creole': 'Crioulo',
      'russian': 'Russo',
      'portuguese': 'Português',
    },
    'ht': {
      'identifyMedication': 'Idantifye medikaman ou imedyatman',
      'scanDescription':
          'Eskane nenpòt boutèy pilil oswa pakè ak AI epi jwenn detay egzak, dozaj, ak enfòmasyon sekirite sou aparèy ou a.',
      'signIn': 'Konekte',
      'email': 'Imèl',
      'password': 'Modpas',
      'rememberMe': 'Sonje mwen',
      'forgotPassword': 'Bliye modpas?',
      'login': 'Konekte',
      'dontHaveAccount': 'Ou pa gen kont?',
      'signUp': 'Enskri',
      'forgotPasswordTitle':
          'Bay imèl ki lye ak kont ou a. N ap voye ou yon lyen pou reyajiste modpas ou nan bwat imèl ou.',
      'verifyCode': 'Verifye kòd',
      'checkYourEmail': 'Tcheke imèl ou',
      'resetLinkSent':
          'Nou voye yon lyen reyajisteman nan mytrek@gmail.com. Antre kòd 5 chif ki mansyone nan imèl la.',
      'havenotReceivedEmail': 'Ou poko resevwa imèl la?',
      'resendCode': 'Voye kòd ankò',
      'setNewPassword': 'Mete yon nouvo modpas',
      'newPasswordHint':
          'Tanpri antre yon nouvo modpas epi re-antre l pou konfime.',
      'newPassword': 'Nouvo Modpas',
      'confirmPassword': 'Konfime Modpas',
      'continue': 'Kontinye',
      'congratulations': 'Felisitasyon!',
      'passwordChanged': 'Modpas chanje',
      'signUpForm': 'Enskri',
      'name': 'Non',
      'confirmPasswordHint': 'Konfime Modpas',
      'signUpButton': 'Enskri',
      'hello': 'Bonjou',
      'healthWealth': 'Sante ou se pi gwo richès ou',
      'scanMedication': 'Eskane Medikaman',
      'scan': 'Eskane',
      'viewDetails': 'Gade detay',
      'dosage': 'Dozaj',
      'genericName': 'Non Jenerik',
      'manufacturer': 'Manifakti',
      'drugClass': 'Klas Medikaman',
      'uses': 'Itilizasyon',
      'dosageInfo': 'Enfòmasyon sou Dozaj',
      'howToTake': 'Kijan pou pran',
      'sideEffects': 'Efè segondè',
      'warnings': 'Avètisman',
      'storageInstructions': 'Enstriksyon Estokaj',
      'interactions': 'Entèraksyon',
      'save': 'Anrejistre',
      'home': 'Akèy',
      'medications': 'Medikaman',
      'settings': 'Paramèt',
      'checkInfo': 'Tcheke enfòmasyon',
      'editProfile': 'Modifye pwofil',
      'languageSelection': 'Seleksyon Lang',
      'aboutUs': 'Konsènan nou',
      'contactUs': 'Kontakte nou',
      'notification': 'Notifikasyon',
      'logout': 'Dekonekte',
      'changePhoto': 'Chanje foto',
      'fullName': 'Non konplè',
      'saveChanges': 'Anrejistre chanjman',
      'searchLanguage': 'Chèche lang',
      'english': 'Angle',
      'spanish': 'Panyòl',
      'french': 'Franse',
      'german': 'Alman',
      'chinese': 'Chinwa',
      'creole': 'Kreyòl',
      'russian': 'Ris',
      'portuguese': 'Pòtigè',
    },
    'zh-CN': {
      'identifyMedication': '即时识别您的药物',
      'scanDescription': '使用AI扫描任何药瓶或包装,在您的设备上获取准确的详细信息、剂量和安全信息。',
      'signIn': '登录',
      'email': '电子邮件',
      'password': '密码',
      'rememberMe': '记住我',
      'forgotPassword': '忘记密码?',
      'login': '登录',
      'dontHaveAccount': '还没有账户?',
      'signUp': '注册',
      'forgotPasswordTitle': '提供与您的帐户关联的电子邮件。我们将向您的收件箱发送密码重置链接。',
      'verifyCode': '验证代码',
      'checkYourEmail': '检查您的电子邮件',
      'resetLinkSent': '我们已向mytrek@gmail.com发送了重置链接。输入电子邮件中提到的5位数代码。',
      'havenotReceivedEmail': '还没收到邮件?',
      'resendCode': '重新发送代码',
      'setNewPassword': '设置新密码',
      'newPasswordHint': '请输入新密码并重新输入以确认。',
      'newPassword': '新密码',
      'confirmPassword': '确认密码',
      'continue': '继续',
      'congratulations': '恭喜!',
      'passwordChanged': '密码已更改',
      'signUpForm': '注册',
      'name': '姓名',
      'confirmPasswordHint': '确认密码',
      'signUpButton': '注册',
      'hello': '你好',
      'healthWealth': '健康是您最大的财富',
      'scanMedication': '扫描药物',
      'scan': '扫描',
      'viewDetails': '查看详情',
      'dosage': '剂量',
      'genericName': '通用名称',
      'manufacturer': '制造商',
      'drugClass': '药物类别',
      'uses': '用途',
      'dosageInfo': '剂量信息',
      'howToTake': '如何服用',
      'sideEffects': '副作用',
      'warnings': '警告',
      'storageInstructions': '储存说明',
      'interactions': '相互作用',
      'save': '保存',
      'home': '首页',
      'medications': '药物',
      'settings': '设置',
      'checkInfo': '检查信息',
      'editProfile': '编辑个人资料',
      'languageSelection': '语言选择',
      'aboutUs': '关于我们',
      'contactUs': '联系我们',
      'notification': '通知',
      'logout': '退出',
      'changePhoto': '更改照片',
      'fullName': '全名',
      'saveChanges': '保存更改',
      'searchLanguage': '搜索语言',
      'english': '英语',
      'spanish': '西班牙语',
      'french': '法语',
      'german': '德语',
      'chinese': '中文',
      'creole': '克里奥尔语',
      'russian': '俄语',
      'portuguese': '葡萄牙语',
    },
    'ru': {
      'identifyMedication': 'Мгновенно определите ваше лекарство',
      'scanDescription':
          'Отсканируйте любой флакон с таблетками или упаковку с помощью ИИ и получите точные детали, дозировку и информацию о безопасности прямо на вашем устройстве.',
      'signIn': 'Войти',
      'email': 'Электронная почта',
      'password': 'Пароль',
      'rememberMe': 'Запомнить меня',
      'forgotPassword': 'Забыли пароль?',
      'login': 'Войти',
      'dontHaveAccount': 'Нет аккаунта?',
      'signUp': 'Зарегистрироваться',
      'forgotPasswordTitle':
          'Укажите электронную почту, связанную с вашей учетной записью. Мы отправим ссылку для сброса пароля в ваш почтовый ящик.',
      'verifyCode': 'Проверить код',
      'checkYourEmail': 'Проверьте свою почту',
      'resetLinkSent':
          'Мы отправили ссылку для сброса на mytrek@gmail.com. Введите 5-значный код, указанный в письме.',
      'havenotReceivedEmail': 'Еще не получили письмо?',
      'resendCode': 'Отправить код повторно',
      'setNewPassword': 'Установить новый пароль',
      'newPasswordHint':
          'Пожалуйста, введите новый пароль и введите его еще раз для подтверждения.',
      'newPassword': 'Новый пароль',
      'confirmPassword': 'Подтвердите пароль',
      'continue': 'Продолжить',
      'congratulations': 'Поздравляем!',
      'passwordChanged': 'Пароль изменен',
      'signUpForm': 'Регистрация',
      'name': 'Имя',
      'confirmPasswordHint': 'Подтвердите пароль',
      'signUpButton': 'Зарегистрироваться',
      'hello': 'Привет',
      'healthWealth': 'Ваше здоровье - ваше величайшее богатство',
      'scanMedication': 'Сканировать лекарство',
      'scan': 'Сканировать',
      'viewDetails': 'Посмотреть детали',
      'dosage': 'Дозировка',
      'genericName': 'Общее название',
      'manufacturer': 'Производитель',
      'drugClass': 'Класс препарата',
      'uses': 'Применение',
      'dosageInfo': 'Информация о дозировке',
      'howToTake': 'Как принимать',
      'sideEffects': 'Побочные эффекты',
      'warnings': 'Предупреждения',
      'storageInstructions': 'Инструкции по хранению',
      'interactions': 'Взаимодействия',
      'save': 'Сохранить',
      'home': 'Главная',
      'medications': 'Лекарства',
      'settings': 'Настройки',
      'checkInfo': 'Проверить информацию',
      'editProfile': 'Редактировать профиль',
      'languageSelection': 'Выбор языка',
      'aboutUs': 'О нас',
      'contactUs': 'Связаться с нами',
      'notification': 'Уведомление',
      'logout': 'Выйти',
      'changePhoto': 'Изменить фото',
      'fullName': 'Полное имя',
      'saveChanges': 'Сохранить изменения',
      'searchLanguage': 'Поиск языка',
      'english': 'Английский',
      'spanish': 'Испанский',
      'french': 'Французский',
      'german': 'Немецкий',
      'chinese': 'Китайский',
      'creole': 'Креольский',
      'russian': 'Русский',
      'portuguese': 'Португальский',
    },
  };
}
